apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        envFrom:
        - configMapRef:
            name: advertisement-config
        image: food-delivery/wallet-service:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 8120
          initialDelaySeconds: 30
          periodSeconds: 10
        name: wallet-service
        ports:
        - containerPort: 8120
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: 8120
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
